package infra

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"text/template"
)

// ComposeRunner manages Docker Compose projects for preview deployments.
type ComposeRunner struct{}

func NewComposeRunner() *ComposeRunner {
	return &ComposeRunner{}
}

const overrideTemplate = `# Auto-generated by orchestrator — do not edit.
services:
  {{.ServiceName}}:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{.RouterName}}.rule=Host(` + "`" + `{{.Host}}` + "`" + `)"
      - "traefik.http.routers.{{.RouterName}}.entrypoints=websecure"
      - "traefik.http.routers.{{.RouterName}}.tls.certresolver=le"
      - "traefik.http.services.{{.RouterName}}.loadbalancer.server.port={{.Port}}"
    networks:
      - default
      - preview-net
    environment:
      - BASE_URL=https://{{.Host}}

networks:
  preview-net:
    external: true
`

type overrideData struct {
	ServiceName string
	RouterName  string
	Host        string
	Port        int
}

// GenerateOverride writes a compose override file with Traefik labels and network config.
// Returns the path to the override file (placed next to the main compose file).
func (r *ComposeRunner) GenerateOverride(workDir, serviceName, routerName, host string, port int) (string, error) {
	tmpl, err := template.New("override").Parse(overrideTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, overrideData{
		ServiceName: serviceName,
		RouterName:  routerName,
		Host:        host,
		Port:        port,
	})
	if err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	overridePath := filepath.Join(workDir, ".productbuilding", "preview", "docker-compose.override.yml")
	if err := os.MkdirAll(filepath.Dir(overridePath), 0755); err != nil {
		return "", fmt.Errorf("create override dir: %w", err)
	}
	if err := os.WriteFile(overridePath, buf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("write override: %w", err)
	}

	slog.Info("compose override generated", "path", overridePath, "host", host)
	return overridePath, nil
}

// Up builds and starts a compose project.
// extraEnv is a list of "KEY=VALUE" strings added to the subprocess environment,
// making them available for variable substitution in compose files.
func (r *ComposeRunner) Up(ctx context.Context, projectName, workDir string, composeFiles []string, extraEnv []string) error {
	args := []string{"compose", "-p", projectName}
	for _, f := range composeFiles {
		args = append(args, "-f", f)
	}
	args = append(args, "up", "-d", "--build", "--remove-orphans")

	slog.Info("compose up", "project", projectName, "workDir", workDir)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	if len(extraEnv) > 0 {
		cmd.Env = append(os.Environ(), extraEnv...)
	}
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose up failed: %w\n%s", err, output)
	}

	slog.Info("compose up complete", "project", projectName)
	return nil
}

// Down stops and removes a compose project including volumes.
func (r *ComposeRunner) Down(ctx context.Context, projectName, workDir string) error {
	args := []string{"compose", "-p", projectName, "down", "-v", "--remove-orphans"}

	slog.Info("compose down", "project", projectName)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose down failed: %w\n%s", err, output)
	}

	slog.Info("compose down complete", "project", projectName)
	return nil
}

// IsRunning reports whether at least one container belonging to the given
// compose project is currently running. Used by startup reconciliation to
// detect previews that the DB believes are alive but whose containers are gone
// (e.g. after EC2 replacement).
func (r *ComposeRunner) IsRunning(ctx context.Context, projectName string) (bool, error) {
	cmd := exec.CommandContext(ctx, "docker", "ps",
		"--filter", "label=com.docker.compose.project="+projectName,
		"--format", "{{.ID}}",
		"--quiet")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return false, fmt.Errorf("docker ps failed: %w\n%s", err, output)
	}
	return len(bytes.TrimSpace(output)) > 0, nil
}

// Exec runs a command in a running service container.
func (r *ComposeRunner) Exec(ctx context.Context, projectName, serviceName, workDir string, command []string) error {
	args := []string{"compose", "-p", projectName, "exec", serviceName}
	args = append(args, command...)

	slog.Info("compose exec", "project", projectName, "service", serviceName, "cmd", command)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose exec failed: %w\n%s", err, output)
	}

	slog.Info("compose exec complete", "project", projectName, "service", serviceName)
	return nil
}

// Logs streams container logs to the provided writer.
func (r *ComposeRunner) Logs(ctx context.Context, projectName, serviceName string, tail int, follow bool, w io.Writer) error {
	args := []string{"compose", "-p", projectName, "logs", serviceName}

	if tail > 0 {
		args = append(args, "--tail", strconv.Itoa(tail))
	}

	if follow {
		args = append(args, "--follow")
	}

	slog.Info("compose logs", "project", projectName, "service", serviceName, "tail", tail, "follow", follow)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Stdout = w
	cmd.Stderr = w

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("compose logs failed: %w", err)
	}

	return nil
}

// LogsFromFile streams logs from files inside a container using tail.
func (r *ComposeRunner) LogsFromFile(ctx context.Context, projectName, serviceName, workDir, logPath string, tail int, follow bool, w io.Writer) error {
	tailArgs := []string{"tail", "-n", strconv.Itoa(tail)}
	if follow {
		tailArgs = append(tailArgs, "-f")
	}
	tailArgs = append(tailArgs, logPath)

	args := []string{"compose", "-p", projectName, "exec", serviceName}
	args = append(args, tailArgs...)

	slog.Info("compose logs from file", "project", projectName, "service", serviceName, "path", logPath, "tail", tail, "follow", follow)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	cmd.Stdout = w
	cmd.Stderr = w

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("compose logs from file failed: %w", err)
	}

	return nil
}
