package infra

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

// ComposeRunner manages Docker Compose projects for preview deployments.
type ComposeRunner struct{}

func NewComposeRunner() *ComposeRunner {
	return &ComposeRunner{}
}

const overrideTemplate = `# Auto-generated by orchestrator — do not edit.
services:
  {{.ServiceName}}:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{.RouterName}}.rule=Host(` + "`" + `{{.Host}}` + "`" + `)"
      - "traefik.http.routers.{{.RouterName}}.entrypoints=websecure"
      - "traefik.http.routers.{{.RouterName}}.tls.certresolver=le"
      - "traefik.http.services.{{.RouterName}}.loadbalancer.server.port={{.Port}}"
    networks:
      - default
      - preview-net
    environment:
      - BASE_URL=https://{{.Host}}

networks:
  preview-net:
    external: true
`

type overrideData struct {
	ServiceName string
	RouterName  string
	Host        string
	Port        int
}

// GenerateOverride writes a compose override file with Traefik labels and network config.
// Returns the path to the override file (placed next to the main compose file).
func (r *ComposeRunner) GenerateOverride(workDir, serviceName, routerName, host string, port int) (string, error) {
	tmpl, err := template.New("override").Parse(overrideTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, overrideData{
		ServiceName: serviceName,
		RouterName:  routerName,
		Host:        host,
		Port:        port,
	})
	if err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	overridePath := filepath.Join(workDir, ".productbuilding", "preview", "docker-compose.override.yml")
	if err := os.MkdirAll(filepath.Dir(overridePath), 0755); err != nil {
		return "", fmt.Errorf("create override dir: %w", err)
	}
	if err := os.WriteFile(overridePath, buf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("write override: %w", err)
	}

	slog.Info("compose override generated", "path", overridePath, "host", host)
	return overridePath, nil
}

// Up builds and starts a compose project.
func (r *ComposeRunner) Up(ctx context.Context, projectName, workDir string, composeFiles []string) error {
	args := []string{"compose", "-p", projectName}
	for _, f := range composeFiles {
		args = append(args, "-f", f)
	}
	args = append(args, "up", "-d", "--build", "--remove-orphans")

	slog.Info("compose up", "project", projectName, "workDir", workDir)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose up failed: %w\n%s", err, output)
	}

	slog.Info("compose up complete", "project", projectName)
	return nil
}

// Down stops and removes a compose project including volumes.
func (r *ComposeRunner) Down(ctx context.Context, projectName, workDir string) error {
	args := []string{"compose", "-p", projectName, "down", "-v", "--remove-orphans"}

	slog.Info("compose down", "project", projectName)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose down failed: %w\n%s", err, output)
	}

	slog.Info("compose down complete", "project", projectName)
	return nil
}

// Exec runs a command in a running service container.
func (r *ComposeRunner) Exec(ctx context.Context, projectName, serviceName, workDir string, command []string) error {
	args := []string{"compose", "-p", projectName, "exec", serviceName}
	args = append(args, command...)

	slog.Info("compose exec", "project", projectName, "service", serviceName, "cmd", command)

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = workDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("compose exec failed: %w\n%s", err, output)
	}

	slog.Info("compose exec complete", "project", projectName, "service", serviceName)
	return nil
}
